---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: etcd-metrics
  name: etcd-metrics
spec:
  endpoints:
    - interval: 15s
      port: metrics
  jobLabel: etcd-metrics
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app: etcd-metrics
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd-metrics
  name: etcd-metrics
spec:
  ports:
    - name: metrics
      port: 2378
      protocol: TCP
  selector:
    component: kube-apiserver