---

- name: Ensuring /var/log/journal is present
  file:
    name: /var/log/journal
    state: directory
  notify: restart journald

- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Configuring network
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present

- name: Adding kubernetes repository
  yum_repository:
    name: Kubernetes
    description: "Kubernetes binary repository"
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    state: present
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey:
    - 'https://packages.cloud.google.com/yum/doc/yum-key.gpg'
    - 'https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg'
    
- name: Making sure kubelet, kubectl, kubeadm, cri-tools are installed
  yum:
    name:
      - kubelet-{{ kubelet_version }}
      - kubeadm-{{ kubeadm_version }}
      - kubectl-{{ kubectl_version }}
      - kubernetes-cni
      - cri-tools-{{ critools_version }}
    state: present
    update_cache: yes

- name: Ensuring kubelet extra-args are present on machine
  template:
    src: kubelet_default.j2
    dest: /etc/sysconfig/kubelet
  notify: restart kubelet

- name: starting and enabling kubelet
  systemd:
    name: kubelet
    state: started
    enabled: yes
    daemon_reload: yes
