---
- name: Installing docker
  include_tasks: "docker.yml"

- name: Installing docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.22.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0750
